
services:

  keycloak:
    environment:
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    
  gateway:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
  identity-service:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
  catalog-service:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER}
        - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}
networks:
  livelearn-private-network:
    internal: false
