services:

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: src/gateway/LiveLearn.Gateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5001
    networks:
      - livelearn-private-network
  
  identity-service:
    image: ${DOCKER_REGISTRY-}identity-service
    build:
      context: .
      dockerfile: src/services/Identity/LiveLearn.Identity.API/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5002
      - ConnectionStrings__UsersDb=Host=postgres;Port=5432;Database=livelearn_identity;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - livelearn-private-network

  postgres:
    image: postgres:18
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGTZ: Europe/Kyiv
    volumes:
      - pgdata:/var/lib/postgresql
      - ./src/infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - livelearn-private-network

  mongo:
    image: mongo:8.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - livelearn-private-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - "6379:6379"
    networks:
      - livelearn-private-network

  rabbitmq:
    image: rabbitmq:4.3.1-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      # - "5672:5672"
      - "15672:15672"
    networks:
      - livelearn-private-network

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - livelearn-private-network
      - livelearn-public-network
  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./src/infrastructure/minio/init.sh:/init.sh
    entrypoint: /bin/sh /init.sh
    environment:
      MINIO_ENDPOINT_URL: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - livelearn-private-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    volumes:
      - ./src/infrastructure/keycloak:/opt/keycloak/data/import:ro
    ports:
      - "8080:8080"
    networks:
      - livelearn-private-network
      - livelearn-public-network

  nginx:
    image: nginx:1.30-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/infrastructure/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - gateway
    networks:
      - livelearn-public-network
      - livelearn-private-network

volumes:
  pgdata:
  mongo-data:
  rabbitmq-data:
  minio-data:

networks:
  livelearn-public-network:
  livelearn-private-network:
    driver: bridge
    internal: true