<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Shared/LiveLearn.BuildingBlocks/LiveLearn.BuildingBlocks.csproj" />
    <ProjectReference Include="../../../Shared/LiveLearn.Contracts/LiveLearn.Contracts.csproj" />
    <ProjectReference Include="../LiveLearn.Catalog.Domain/LiveLearn.Catalog.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
