<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LiveLearn.Assessment.Application\LiveLearn.Assessment.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\LiveLearn.Contracts\LiveLearn.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
