<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Shared/LiveLearn.BuildingBlocks/LiveLearn.BuildingBlocks.csproj" />
    <ProjectReference Include="../LiveLearn.Identity.Application/LiveLearn.Identity.Application.csproj" />
  </ItemGroup>

</Project>
